//! Compile-time tool submission via [`inventory`] and the runtime
//! [`PluginToolRegistry`] that collects them.
//!
//! # How it works
//!
//! Each plugin crate annotates its tool handler functions with `#[tool]` (from
//! `tool_registry_macros`).  The macro emits an `inventory::submit!` call that
//! registers an [`InventoryEntry`] in the plugin's binary segment.
//!
//! At start-up, call [`PluginToolRegistry::from_namespace`] to harvest all
//! entries whose namespace begins with your plugin's module path, then merge the
//! result into the central [`ToolRegistry`].
//!
//! # Example (plugin crate)
//!
//! ```rust,ignore
//! use tool_registry_macros::tool;
//! use serde_json::Value;
//!
//! #[tool(category = "math")]
//! /// Add two integers.
//! pub fn add(a: i64, b: i64) -> anyhow::Result<Value> {
//!     Ok(serde_json::json!({ "result": a + b }))
//! }
//!
//! // In your plugin initialisation:
//! pub fn plugin_tools() -> tool_registry::PluginToolRegistry {
//!     tool_registry::PluginToolRegistry::from_namespace(module_path!())
//! }
//! ```

use std::sync::Arc;

use crate::tool::ChatTool;
use crate::ToolContext;
use serde_json::Value;

// ────────────────────────────────────────────────────────────────────────────
// Inventory entry — the static record emitted by #[tool]
// ────────────────────────────────────────────────────────────────────────────

/// A compile-time record submitted by the `#[tool]` macro via `inventory::submit!`.
///
/// You never construct this manually; it is generated by the macro.
pub struct InventoryEntry {
    /// Rust module path of the crate that defined this tool (used for namespacing).
    pub namespace: &'static str,

    /// JSON-encoded [`ToolDefinition`](crate::ToolDefinition).
    pub definition_json: &'static str,

    /// Markdown documentation string (auto-generated or from an external file).
    pub documentation: &'static str,

    /// Raw function pointer that deserialises JSON args and calls the real fn.
    pub handler: fn(Value, &ToolContext) -> anyhow::Result<Value>,
}

inventory::collect!(InventoryEntry);

// ────────────────────────────────────────────────────────────────────────────
// Adaptor: wrap an InventoryEntry in Arc<dyn ChatTool>
// ────────────────────────────────────────────────────────────────────────────

struct InventoryTool {
    name: &'static str,
    description: &'static str,
    category: Option<&'static str>,
    parameters_schema: Value,
    handler: fn(Value, &ToolContext) -> anyhow::Result<Value>,
}

impl ChatTool for InventoryTool {
    fn name(&self) -> &str { self.name }
    fn description(&self) -> &str { self.description }
    fn category(&self) -> Option<&str> { self.category }
    fn parameters_schema(&self) -> Value { self.parameters_schema.clone() }

    fn execute(&self, args: Value, ctx: &ToolContext) -> anyhow::Result<Value> {
        (self.handler)(args, ctx)
    }
}

// ────────────────────────────────────────────────────────────────────────────
// PluginToolRegistry
// ────────────────────────────────────────────────────────────────────────────

/// A set of tools contributed by a single plugin, assembled at start-up from
/// `inventory` entries or by explicit registration.
pub struct PluginToolRegistry {
    tools: Vec<Arc<dyn ChatTool>>,
}

impl PluginToolRegistry {
    /// Collect all [`InventoryEntry`]s whose `namespace` starts with `prefix`.
    ///
    /// Pass `module_path!()` as `prefix` from the plugin's init code so only
    /// that plugin's tools are included.
    pub fn from_namespace(prefix: &str) -> Self {
        let tools = inventory::iter::<InventoryEntry>
            .into_iter()
            .filter(|e| e.namespace.starts_with(prefix))
            .filter_map(|e| parse_inventory_entry(e).ok())
            .collect();

        Self { tools }
    }

    /// Collect *all* [`InventoryEntry`]s from every linked crate.
    pub fn from_all_inventory() -> Self {
        let tools = inventory::iter::<InventoryEntry>
            .into_iter()
            .filter_map(|e| parse_inventory_entry(e).ok())
            .collect();

        Self { tools }
    }

    /// Create an empty registry and add tools manually.
    pub fn new() -> Self {
        Self { tools: Vec::new() }
    }

    /// Add a pre-built [`ChatTool`] to this plugin registry.
    pub fn add(&mut self, tool: Arc<dyn ChatTool>) {
        self.tools.push(tool);
    }

    /// All tools in this plugin registry.
    pub fn tools(&self) -> impl Iterator<Item = Arc<dyn ChatTool>> + '_ {
        self.tools.iter().cloned()
    }

    /// Number of tools in this registry.
    pub fn len(&self) -> usize {
        self.tools.len()
    }

    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }
}

impl Default for PluginToolRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

fn parse_inventory_entry(entry: &InventoryEntry) -> anyhow::Result<Arc<dyn ChatTool>> {
    let v: Value = serde_json::from_str(entry.definition_json)
        .map_err(|e| anyhow::anyhow!("bad tool definition JSON from '{}': {e}", entry.namespace))?;

    let name: &'static str = Box::leak(
        v.get("name")
            .and_then(|n| n.as_str())
            .ok_or_else(|| anyhow::anyhow!("tool definition missing 'name'"))?
            .to_string()
            .into_boxed_str(),
    );

    let description: &'static str = Box::leak(
        v.get("description")
            .and_then(|d| d.as_str())
            .unwrap_or("")
            .to_string()
            .into_boxed_str(),
    );

    let category: Option<&'static str> = v
        .get("category")
        .and_then(|c| c.as_str())
        .filter(|s| !s.is_empty())
        .map(|s| -> &'static str { Box::leak(s.to_string().into_boxed_str()) });

    let parameters_schema = v
        .get("parameters")
        .cloned()
        .unwrap_or_else(|| serde_json::json!({"type": "object", "properties": {}}));

    Ok(Arc::new(InventoryTool {
        name,
        description,
        category,
        parameters_schema,
        handler: entry.handler,
    }))
}
